name: Test
on: [push pull_request]
jobs:
  run_kvm:
    name: Run KVM test.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Say hi.
        run: |
          echo 'Hi!'
